export const myInfo = {
  "data": {
    "id": 3122680332,
    "idstr": "3122680332",
    "class": 1,
    "screen_name": "usamieiji",
    "name": "usamieiji",
    "province": "34",
    "city": "2",
    "location": "安徽 芜湖",
    "description": "kissme",
    "url": "",
    "profile_image_url": "https://tvax2.sinaimg.cn/crop.0.0.480.480.50/ba20520cly8fqlc1g2c1nj20dc0dcn36.jpg?KID=imgbed,tva&Expires=1593284246&ssig=o0ncRKENDJ",
    "cover_image_phone": "http://ww1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg",
    "profile_url": "u/3122680332",
    "domain": "",
    "weihao": "",
    "gender": "m",
    "followers_count": 120,
    "friends_count": 155,
    "pagefriends_count": 3,
    "statuses_count": 19,
    "video_status_count": 0,
    "video_play_count": 0,
    "favourites_count": 35,
    "created_at": "Sat Jan 12 19:58:32 +0800 2013",
    "following": false,
    "allow_all_act_msg": false,
    "geo_enabled": false,
    "verified": false,
    "verified_type": -1,
    "remark": "",
    "email": "",
    "insecurity": {"sexual_content": false},
    "status": {
      "visible": {"type": 0, "list_id": 0},
      "created_at": "Sat Jun 27 23:57:17 +0800 2020",
      "id": 4520578802081599,
      "idstr": "4520578802081599",
      "mid": "4520578802081599",
      "can_edit": false,
      "show_additional_indication": 0,
      "text": "微博test[可爱]",
      "textLength": 14,
      "source_allowclick": 0,
      "source_type": 2,
      "source": "<a href=\"http://weibo.com/\" rel=\"nofollow\">iPhone客户端</a>",
      "favorited": false,
      "truncated": false,
      "in_reply_to_status_id": "",
      "in_reply_to_user_id": "",
      "in_reply_to_screen_name": "",
      "pic_urls": [{"thumbnail_pic": "http://wx4.sinaimg.cn/thumbnail/ba20520cly1gg7aey1ib7j20ql0qujv2.jpg"}, {"thumbnail_pic": "http://wx1.sinaimg.cn/thumbnail/ba20520cly1gg7aextmhdj20c80c3wet.jpg"}],
      "thumbnail_pic": "http://wx4.sinaimg.cn/thumbnail/ba20520cly1gg7aey1ib7j20ql0qujv2.jpg",
      "bmiddle_pic": "http://wx4.sinaimg.cn/bmiddle/ba20520cly1gg7aey1ib7j20ql0qujv2.jpg",
      "original_pic": "http://wx4.sinaimg.cn/large/ba20520cly1gg7aey1ib7j20ql0qujv2.jpg",
      "geo": null,
      "is_paid": false,
      "mblog_vip_type": 0,
      "annotations": [{"client_mblogid": "iPhone-59BDAB06-B71F-4493-848C-0707D9F249F9"}, {"mapi_request": true}],
      "picStatus": "0:1,1:1",
      "reposts_count": 0,
      "comments_count": 0,
      "attitudes_count": 0,
      "pending_approval_count": 0,
      "isLongText": false,
      "reward_exhibition_type": 0,
      "hide_flag": 0,
      "mlevel": 0,
      "biz_feature": 4294967300,
      "hasActionTypeCard": 0,
      "darwin_tags": [],
      "hot_weibo_tags": [],
      "text_tag_tips": [],
      "mblogtype": 0,
      "rid": "0",
      "userType": 0,
      "more_info_type": 0,
      "positive_recom_flag": 0,
      "content_auth": 0,
      "gif_ids": "",
      "is_show_bulletin": 2,
      "comment_manage_info": {"comment_permission_type": -1, "approval_comment_type": 0},
      "pic_num": 2
    },
    "ptype": 0,
    "allow_all_comment": true,
    "avatar_large": "https://tvax2.sinaimg.cn/crop.0.0.480.480.180/ba20520cly8fqlc1g2c1nj20dc0dcn36.jpg?KID=imgbed,tva&Expires=1593284246&ssig=skcv3ewDLN",
    "avatar_hd": "https://tvax2.sinaimg.cn/crop.0.0.480.480.1024/ba20520cly8fqlc1g2c1nj20dc0dcn36.jpg?KID=imgbed,tva&Expires=1593284246&ssig=z1om1r5KYf",
    "verified_reason": "",
    "verified_trade": "",
    "verified_reason_url": "",
    "verified_source": "",
    "verified_source_url": "",
    "follow_me": false,
    "like": false,
    "like_me": false,
    "online_status": 0,
    "bi_followers_count": 29,
    "lang": "zh-cn",
    "star": 0,
    "mbtype": 0,
    "mbrank": 0,
    "block_word": 0,
    "block_app": 0,
    "credit_score": 80,
    "user_ability": 2098176,
    "urank": 14,
    "story_read_state": -1,
    "vclub_member": 0,
    "is_teenager": 0,
    "is_guardian": 0,
    "is_teenager_list": 0,
    "pc_new": 0,
    "special_follow": false,
    "planet_video": 0,
    "video_mark": 0,
    "live_status": 0
  },
  "status": 200,
  "statusText": "OK",
  "headers": {
    "connection": "close",
    "content-encoding": "gzip",
    "content-type": "application/json;charset=UTF-8",
    "date": "Sat, 27 Jun 2020 15:57:26 GMT",
    "server": "nginx/1.6.1",
    "transfer-encoding": "chunked",
    "vary": "Accept-Encoding",
    "x-powered-by": "Express"
  },
  "config": {
    "url": "/users/show.json",
    "method": "get",
    "params": {"access_token": "2.00on816D081WQLb7cea564750uUe_o", "uid": "3122680332"},
    "headers": {"Accept": "application/json, text/plain, */*"},
    "baseURL": "http://127.0.0.1:8080/api",
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 5000,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  },
  "request": {}
}